# Generated by Django 2.2.9 on 2022-10-03 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220915_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'default_related_name': 'group'},
        ),
    ]
